### ISSUE TITLE
Feature Adding Algorithm Question Binary Tree

### ISSUE THREAD

**Issue by harshkasat** [Pratick9/Hacktoberfest2023-1#8]
I am using the Python language for an algorithm question on LeetCode. Can you please assign it to me?

**Comment by Pratick9** [comment]
Please star this repo for getting merge

**Comment by ShubhamNagure** [comment]
@harshkasat  Is it a valid Repo for hacktoberfest challenge?

**Comment by harshkasat** [comment]
No I just got message from them this pr is excluded.
I'm just teaching my friends how to make pr 😁😁. Now I'm closing pr and issue. Thank for repo. Happy hacking 😄😄
